# Julia Workshop, Day 1: The Basics

Goals for today:

- Get familiar with the basics of Julia and make sure everyone's on the same page
- Install a package
- Use the REPL to get help
- Write some nontrivial programs in it
- Make your own Julia types
- Use multiple dispatch

## The REPL

- By default, you'll get the `julia>` prompt, from which you can write normal Julia code
- Using some special keys, you can enter other modes
- Try `?`: this gets you the `help?>` mode. Try typing `println`
- `;` lets you run shell commands (`cd`, `ls`, etc.)
- Next, use `]` to get to the package manager
  - For now, we'll just install `Revise.jl`, which will make development easier
  - Type `add Revise`, and it'll install
- To use a package, type `using Revise`

## What is and why use Julia?

- Programming language specifically designed for scientific, mathematic, and numeric computing
- Aims to solve the two-language problem
  - Two language problem: when writing in a high-level, dynamic language you get expressiveness but slow code
- Compared to most commonly-used languages:
  - Good package manager and documentation tools
  - Faster than most other dynamically-typed languages (Python, R, MATLAB, etc.)
  - More expressive than most statially-typed languages (C++, FORTRAN, Java, etc.)
- Let's try some things in the REPL!

In [1]:
x = 5

5

In [2]:
α = "Hello"

"Hello"

In [3]:
println("The value of `α` is $(α), and its type is ", typeof(α))

The value of `α` is Hello, and its type is String


In [4]:
if rand(Bool)
    println("Heads")
else
    println("Tails")
end

Tails


In [69]:
# if is an expression!
x = if rand(Bool)
    1
else
    println("it was false")
    2
end
println(x)

it was false
2


In [70]:
function foo(x)
    if x > 5
        2x
    else
        3x
    end
end

println(foo(6))
println(foo(3))

6
12
3
9


In [7]:
quadruple(x) = 4x

quadruple (generic function with 1 method)

- This is exactly equivalent to

```julia
function quadruple(x)
    return 4x
end
```

In [8]:
x = 0
while x < 5
    print(quadruple(x), ", ")
    x += 1
end

0, 4, 8, 12, 16, 

In [9]:
xs = [1, 2, 3, 4, 5]
for x in xs
    print(quadruple(x), ", ")
end

4, 8, 12, 16, 20, 

## Types

- Types play a big role in Julia
- Unlike e.g. Python, Julia doesn't try to hide type from you and types carry more information

In [10]:
typeof(5)

Int64

In [11]:
typeof("Hello")

String

In [12]:
typeof("Goodbye"[1])

Char

In [13]:
typeof(1:5)

UnitRange{Int64}

In [14]:
for i in 1:10
    print(i, ", ")
end

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 

### Arrays

- Julia has built-in multidimensional arrays

In [15]:
xs = [1, 2, 3, 4]

for i in 1:4
    print(xs[i], ", ")
end

1, 2, 3, 4, 

In [16]:
A = [1 2 3; 4 5 6; 7 8 9]
x = [2.0, 3.0, 4.0]

A * x

3-element Vector{Float64}:
 20.0
 47.0
 74.0

- It also has special syntax for broadcasting operations

In [17]:
ℯ ^ A # \euler

3×3 Matrix{Float64}:
 1.11891e6  1.37482e6  1.63072e6
 2.53388e6  3.11342e6  3.69295e6
 3.94886e6  4.85201e6  5.75517e6

In [18]:
ℯ .^ A

3×3 Matrix{Float64}:
    2.71828     7.38906    20.0855
   54.5982    148.413     403.429
 1096.63     2980.96     8103.08

In [19]:
sin.(x)

3-element Vector{Float64}:
  0.9092974268256817
  0.1411200080598672
 -0.7568024953079282

## Guessing Game

- Instructions:
  - Pick a number between 1 and 100
  - Take guesses from the terminal, and say if it's too high or too low
  - Repeat until the right number is entered
  - You might need to wrap the whole thing in a function (example shown below)
- You will need:
  - `rand(a:b)` picks a random integer in $[a, b]$
  - `readline()` reads a line of input from the terminal
  - `parse(Int, s)` parses the `String` `s` as an `Int`
- Optional:
  - Improve the function getting a number so that it asks again if the number is out of range
  - Wrap the script in a function which takes a range
  - Limit the number of guesses so that the player must guess optimally

```julia
function main()
    # your code here
end
main()
```

```julia
number = rand(1:100)

println("Pick a number between 1 and 100:")

get_number() = parse(Int, readline())

input = get_number()

while input != number
    if input > number
        println("Too high!")
    else
        println("Too low!")
    end
    println("Enter another number:")
    input = get_number()
end

println("You got it!")
```

## A Little More of the Language

- Types form a tree, the root of which is `Any`
- Every type is either _abstract_ or _concrete_
  - Only abstract types may have subtypes: no subclasses
  - Values always have a concrete type

![Subtypes Diagram](https://juliaworkshop.miakramer.space/static/subtypes.png)

In [20]:
supertype(Integer)

Real

In [21]:
subtypes(Integer)

3-element Vector{Any}:
 Bool
 Signed
 Unsigned

In [22]:
Int <: Real

true

In [71]:
5 isa Integer

false

In [24]:
isabstracttype(Bool), isabstracttype(Signed)

(false, true)

- Types may have parameters
  - `Vector` is an abstract (-ish) type, `Vector{Float64}` is a list of 64-bit floats
- Note: types are _invariant_ w.r.t. their parameters
  - `Float64 <: Real` but `!(Vector{Float64} <: Vector{Real})`
  - The exception is `Tuple`
- Julia always tries to _infer_ appropriate types

In [25]:
a = [1, 2, 3]
typeof(a)

Vector{Int64} (alias for Array{Int64, 1})

In [26]:
b = [1, 2.0, 3im]
typeof(b)

Vector{ComplexF64} (alias for Array{Complex{Float64}, 1})

In [27]:
c = ["Hello", 5, 1:6]
typeof(c)

Vector{Any} (alias for Array{Any, 1})

- Be careful with types
- Remember, `5 isa Int`, `5 isa Real`, `5 isa Any` and so on
- For parametric types, you want concrete parameters whenever possible
  - We'll talk more about that next time

In [73]:
A = Int[] # Vector{Int64}

push!(A, 1)
push!(A, UInt8(1))
push!(A, 1.5)

LoadError: InexactError: Int64(1.5)

In [75]:
A = Real[]

push!(A, 1)
push!(A, 1.5)
push!(A, π)
# but you almost certainly don't want this...

3-element Vector{Real}:
 1
 1.5
 π = 3.1415926535897...

## Multiple Dispatch

- This is the core paradigm of Julia
  - Called multimethods if you're coming from the Lisp world
- One _function_ may have many _methods_

- We always pick the **most specific** method

In [30]:
bar(x)          = x  # implicitly ::Any
bar(x::Integer) = 2x
bar(x::Int8)    = 3x

bar (generic function with 3 methods)

In [31]:
bar(1.0), bar(1), bar(Int8(1))

(1.0, 2, 3)

In [32]:
@which bar(10)

bar(x::Integer)
     @ Main In[30]:2

In [33]:
@which +(1, 2)

+(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}
     @ Base int.jl:87

In [34]:
@which +(1.0, 2.0)

+(x::T, y::T) where T<:Union{Float16, Float32, Float64}
     @ Base float.jl:408

In [35]:
@which +(1.0, 3.0im)

+(x::Real, z::Complex)
     @ Base complex.jl:328

## Writing Our Own Type

- Let's do integers modulo $n$

In [36]:
struct IntModN <: Integer
    value::Int
    modulus::Int
end

In [37]:
IntModN(10, 3)

IntModN(10, 3)

In [38]:
import Base.show
show(io::IO, x::IntModN) = print(io, "IntModN($(x.value) mod $(x.modulus))")

show (generic function with 286 methods)

In [39]:
IntModN(10, 3)

IntModN(10 mod 3)

In [40]:
struct MismatchedModulusException <: Exception
    first::IntModN
    second::IntModN
end

In [41]:
import Base.+
function +(x::IntModN, y::IntModN)
    if x.modulus != y.modulus
        throw(MismatchedModulusException(x, y))
    end
    IntModN(x.value + y.value, x.modulus)
end

+ (generic function with 208 methods)

In [77]:
IntModN(5, 10) + IntModN(23, 10)

IntModN(28 mod 10)

In [43]:
function congruent(x::IntModN, y::IntModN)
    if x.modulus != y.modulus
        throw(MismatchedModulusException(x, y))
    end
    mod(x.value, x.modulus) == mod(y.value, x.modulus)
end

congruent (generic function with 1 method)

In [79]:
congruent(IntModN(1, 10), IntModN(11, 10))

true

In [80]:
congruent(IntModN(1, 10) + IntModN(1, 10), IntModN(22, 10))

true

## Making Our Own Parametric Type

- We explicitly used `Int` for our storage
- But what if we want to make it generic?
  - For example, if we're dealing with numbers larger than `typemax(Int)`

In [46]:
struct ModN{T <: Integer} <: Integer
    value::T
    modulus::T
end

In [47]:
function show(io::IO, x::ModN{T}) where {T <: Integer}
    print(io, "ModN{$T}($(x.value) mod $(x.modulus))")
end

show (generic function with 287 methods)

In [48]:
ModN(0x1, 0x2)

ModN{UInt8}(1 mod 2)

In [49]:
ModN(1, 2)

ModN{Int64}(1 mod 2)

In [50]:
ModN(0x1, 2)

LoadError: MethodError: no method matching ModN(::UInt8, ::Int64)

Closest candidates are:
  ModN(::T, ::T) where T<:Integer
   @ Main In[46]:2
  (::Type{T})(::T) where T<:Number
   @ Core boot.jl:792


## Promotion

- To do operations like `+` and `*` on different types, Julia _widens_ one type
- For example, `+(1.0, 1)` is essentially `+(1.0, convert(Float64, 1))`
- Julia picks the type using `promote_rule`

In [51]:
promote(1.0, 1)

(1.0, 1.0)

In [52]:
promote_rule(Float64, Int64)

Float64

- So, let's use this system!
- We'll define constructors for `ModN`
  - Constructors in Julia are just functions that have the same name as the type
- We saw before that we had a method `ModN(::T, ::T) where {T <: Integer}`

In [53]:
ModN(value::Integer, modulus::Integer) = ModN(promote(value, modulus)...)

ModN

In [54]:
ModN(0x1, 2)

ModN{Int64}(1 mod 2)

In [55]:
function +(x::ModN{T}, y::ModN{U}) where {T, U}
    if x.modulus != y.modulus
        throw(MismatchedModulusException(x, y))
    end
    ModN(x.value + y.value, x.modulus)
end

function congruent(x::ModN, y::ModN)
    if x.modulus != y.modulus
        throw(MismatchedModulusException(x, y))
    end
    mod(x.value, x.modulus) == mod(y.value, y.modulus)
end

congruent (generic function with 2 methods)

In [56]:
ModN(0x1, 0x5) + ModN(1, 5)

ModN{Int64}(2 mod 5)

## Iterators

- One use of dispatch: easy to iterate!
- If you have a type `Iter` which you'd like to iterate over, you just need to define two methods of `iterate`
- So, if we wanted to replicate list iteration:

In [57]:
struct MyVector{Element}
    vector::Vector{Element}
end

In [58]:
import Base: iterate

# first method: return (first_item, next_state)
iterate(v::MyVector) = if length(v.vector) == 0
    nothing
else
    (v.vector[1], 2)
end

# second method: return (next_item, next_state)
iterate(v::MyVector, state) = if state > length(v.vector)
    nothing
else
    (v.vector[state], state + 1)
end

iterate (generic function with 248 methods)

In [59]:
v = MyVector(['a', 'b', 'c', 'd', 'e'])
for x in v
    println(x)
end

a
b
c
d
e


- Example: iterating over the first $n$ squares

In [60]:
struct Squares
    max::Int
end

In [61]:
# first method: return (first_item, next_state)
iterate(::Squares) = (1, 2)
# second method: return (next_item, next_state)
iterate(s::Squares, i::Int) = if i > s.max
    nothing
else
    (i^2, i + 1)
end

iterate (generic function with 250 methods)

In [62]:
for s in Squares(5)
    print(s, ", ")
end

1, 4, 9, 16, 25, 

In [63]:
s = Squares(5)

iterated_item, next_state = iterate(s)
println((iterated_item, next_state))

iterated_item, next_state = iterate(s, next_state)
println((iterated_item, next_state))

iterated_item, next_state = iterate(s, next_state)
println((iterated_item, next_state))

iterated_item, next_state = iterate(s, next_state)
println((iterated_item, next_state))

iterated_item, next_state = iterate(s, next_state)
println((iterated_item, next_state))

iter = iterate(s, next_state)
println(iter)

(1, 2)
(4, 3)
(9, 4)
(16, 5)
(25, 6)
nothing


To explain, Julia turns:

```julia
for x in iterable
    # do something
end
```

into:

```julia
next = iterate(iterable)
while !isnothing(next)
    (x, state) = next
    # do something
    next = iterate(iterable, state)
end
```

### Aside: Dispatch and Defaults

- Julia (like many languages) has default parameters
- In Python:

```python
>>> def f(x, y=0):
...     print(f"({x}, {y})")
... 
>>> f(1, 2)
(1, 2)
>>> f(1)
(1, 0)
>>> 
```

- In Julia, we do it through dispatch rather than through function call magic

```julia
hasdefault(x, y=0) = println("($x, $y)")
```

is the same as:

In [64]:
hasdefault(x, y) = println("($x, $y)")
hasdefault(x) = hasdefault(x, 0)
hasdefault(1)
hasdefault(1, 2)

(1, 0)
(1, 2)


- So, this would've worked as well:

```julia
iterate(s::Squares, i::Int=1) = if i > s.max
    nothing
else
    (i^2, i + 1)
end
```

## Interfaces

- This iteration is an example of one of Julia's _interfaces_
- Unlike e.g. Rust or Haskell, Julia's interfaces are informal and not checked by the compiler during compilation
- But they are still powerful!
- Other useful interfaces:
  - Indexing
  - Array

## Last Exercise of the Evening

- Write a type which represents all multiples of integers up to `n`
    - I.e. if you build it with `factor = 1.5` and `n = 4`, iterating over it should produce `1.5, 3.0, 4.5, 6.0`
- It should store `n` as an `Int`, but have a type parameter `{T <: Number}` for `factor`
- Write the two `iterate` methods for it
    - [docs.julialang.org/en/v1/manual/interfaces/](https://docs.julialang.org/en/v1/manual/interfaces/)
- Then, using the documentation linked above, write a `length` method and a `getindex` method for it
- Bonus: what is `eltype` for this type?

In [65]:
struct Multiples{T <: Number}
    n::Int
    factor::T
end

function iterate(m::Multiples)
    if m.n == 0
        return nothing
    else
        return (m.factor * 1, 2)
    end
end

function iterate(m::Multiples, state::Int)
    if state > m.n
        return nothing
    else
        return (m.factor * state, state + 1)
    end
end

function iterate(m::Multiples{T}, state::Int) where {T <: Integer} = ...

iterate (generic function with 252 methods)

In [66]:
m = Multiples(5, 1.5)
println(m)
for x in m
    println(x)
end

Multiples{Float64}(5, 1.5)
1.5
3.0
4.5
6.0
7.5


In [67]:
m = Multiples(3, im)
println(m)
for x in m
    println(x)
end

Multiples{Complex{Bool}}(3, im)
0 + 1im
0 + 2im
0 + 3im


## In Summary

- Julia's REPL is very useful, and often if you forget something just ask it!
- Julia is a very expressive language, and the type system is a major part of that
- Types form a hierarchy, and are either concrete or abstract
- Types may have parameters
- We can write our own types and stick them in the hierarchy
  - We can get operations like `+` using dispatch
- We can do operations on different types using the promotion system

## Problems 

- Three short problems, more detailed description is in the starter code
  - [juliaworkshop.miakramer.space](https://juliaworkshop.miakramer.space)
- Problem 1: Write an iterator over the primes $\leq n$
  - Write a type, write some simple code, use the iterator methods
- Problem 2: Write an array type which is the outer product of two vectors
  - Write a matrix type, fill in a couple methods and it's fully functional!
  - (This makes efficient representations very easy!)
- Problem 3: Peano Arithmetic
  - Get more comfortable with dispatch and recursion
  - (Just don't try too large of problems, this one's a workout for the compiler)